<a href="https://colab.research.google.com/github/memari-majid/Algorithms/blob/main/sparse_mat_mult_dict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sparse Matrices Multiplication
### Creating dictionary of non-zero elements

In [14]:
def get_dict_of_nonzeros(matrix):
    dict_of_nonzero_cells = {}
    for i in range(len(matrix)):
      for j in range(len(matrix[0])):
        if matrix[i][j] != 0:
            dict_of_nonzero_cells[(i,j)] = matrix[i][j]
    return dict_of_nonzero_cells

### Creating random sparse matrices

In [15]:
import numpy as np
mat1 = np.random.randint(2,size=(3,5))
print(mat1)
mat2 = np.random.randint(2,size=(5,4))
print(mat2)

[[1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 1 1]]
[[0 0 1 1]
 [0 1 0 0]
 [0 0 0 1]
 [0 1 1 1]
 [1 1 0 1]]


In [16]:
if len(mat1[0]) != len(mat2):
  print('Matrix-1 col not equal to Matrix-2 row')
sparse_a = get_dict_of_nonzeros(mat1)
print('First sparse matrix dict key=(row,col),value=element')
print(sparse_a)
print('Second sparse matrix dict key=(row,col),value=element')
sparse_b = get_dict_of_nonzeros(mat2)
print(sparse_b) 
matrix_c = [[0] * len(mat2[0]) for _ in range(len(mat1))]

First sparse matrix dict key=(row,col),value=element
{(0, 0): 1, (1, 0): 1, (1, 1): 1, (1, 4): 1, (2, 3): 1, (2, 4): 1}
Second sparse matrix dict key=(row,col),value=element
{(0, 2): 1, (0, 3): 1, (1, 1): 1, (2, 3): 1, (3, 1): 1, (3, 2): 1, (3, 3): 1, (4, 0): 1, (4, 1): 1, (4, 3): 1}


In [18]:
# itertate through matrix-1 non-zeros
for i, k in sparse_a.keys():
  # iterate through all matrix-2 columns
  for j in range(len(mat2[0])):
    # check if the respecive non-zero exists in the second sparse matrix
    if (k,j) in sparse_b.keys():
      print(f'{matrix_c[i][j]} = {sparse_a[(i,k)]} * {sparse_b[(k,j)]}')
      matrix_c[i][j] += sparse_a[(i,k)] * sparse_b[(k,j)]

1 = 1 * 1
1 = 1 * 1
1 = 1 * 1
2 = 1 * 1
2 = 1 * 1
1 = 1 * 1
3 = 1 * 1
3 = 1 * 1
2 = 1 * 1
1 = 1 * 1
2 = 1 * 1
1 = 1 * 1
3 = 1 * 1
3 = 1 * 1


In [19]:
print(matrix_c)

[[0, 0, 2, 2], [2, 4, 2, 4], [2, 4, 2, 4]]
